'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider} from "./Context/Auth-context";
import { useAuth } from '@/app/Context/Auth-context';
import { ReactNode } from 'react'
import AuthLayout from "./auth/layout";
import { redirect } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const AuthLayout1  =  ({ children }: { children: ReactNode }) => {
  const { login} = useAuth(); // useAuth se usa aquí, dentro del árbol de AuthProvider
return null;
  
  return (
    <>
      {children}
    </>
  );
};

export default function RootLayout({ children }: { children: ReactNode }) {
  
  
  
  return (
    <AuthProvider>
      <html lang="en">
        <body>
    {children}
        </body>
      </html>
    </AuthProvider>)
     {/*

  if (!isAuthenticated) {
    // Si no está autenticado, redirige al usuario y no renderiza nada más
    redirect('/');
    }
      <AuthLayout1>
            {children}
          </AuthLayout1>
  
  <html lang="en">
    <body>{children}</body>
  </html>)

     */} 
}




